# Generated by Django 3.0.3 on 2020-07-15 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddClassModel',
            fields=[
                ('Idno', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20, unique=True)),
                ('Faculty', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Fee', models.FloatField()),
                ('Duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('Contactno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('emailid', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EnroleListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contanctno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.StudentModel')),
                ('idno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.AddClassModel')),
            ],
        ),
    ]
